name: CI-pipe

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: 1. code checkout
        uses: actions/checkout@v4

      - name: 2. setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 3. install npm
        run: npm install

      - name: 4. audit check
        run: npm audit --audit-level=high


      - name: 5. docker image build
        run: docker build -t pass-gen-app .

      - name: 6. trivy scan
        uses: aquasecurity/trivy-action@master
        with: 
          image-ref: pass-gen-app
          severity: CRITICAL
          exit-code: 1







        

